### ISSUE TITLE
Update for MCBE 1.14.60

### ISSUE THREAD

**Issue by GamingFR91** [ItzLightyHD/MultiProtocol#1]
We need an update for MCBE 1.14.60

If you use this version of the plugin on PM-MP for MCBE 1.14.60, it will make "internal server error" on older MCPE versions

**Comment by ItzLightyHD** [comment]
> We need an update for MCBE 1.14.60
> 
> If you use this version of the plugin on PM-MP for MCBE 1.14.60, it will make "internal server error" on older MCPE versions

It supports 1.13x, but not below 1.13 due to MCPE skin system changed on PocketMine too.

**Comment by GamingFR91** [comment]
It work on 1.14.x but not on 1.14.60

**Comment by GamingFR91** [comment]
> > We need an update for MCBE 1.14.60
> > If you use this version of the plugin on PM-MP for MCBE 1.14.60, it will make "internal server error" on older MCPE versions
> 
> It supports 1.13x, but not below 1.13 due to MCPE skin system changed on PocketMine too.

It work on 1.14.x bot not on 1.14.60

**Comment by ItzLightyHD** [comment]
Try to use it in 1.14.0 PMMP, it will probably work

**Comment by GamingFR91** [comment]
I know but it work with desktop player, if you use it on PocketMine 1.14.x, it work with some Mobile player, the others mobile players, their Game crash

**Comment by ItzLightyHD** [comment]
I discovered that you can’t enter in servers with 1.14x with 1.14.60. Only some other plugins can work anyway, sorry.
